name: Deploy Redis Service
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SWECC_REDIS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/swecc-redis:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/swecc-redis:${{ github.sha }}

  deploy_to_swarm:
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]

    needs: push_to_dockerhub

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub on deployment server
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SWECC_REDIS_TOKEN }}

      - name: Pull latest image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/swecc-redis:latest

      - name: Deploy Redis service
        run: |
          if docker service ls | grep -q "redis"; then
            docker service update \
              --image ${{ secrets.DOCKERHUB_USERNAME }}/swecc-redis:latest \
              --update-parallelism 1 \
              --update-delay 30s \
              --update-order start-first \
              --update-failure-action continue \
              --limit-cpu 0.3 \
              --limit-memory 256M \
              --reserve-cpu 0.1 \
              --reserve-memory 128M \
              --with-registry-auth \
              redis
          else
            docker service rm redis || true

            docker service create \
              --name redis \
              --network prod_swecc-network \
              --mount type=volume,source=redis_data,target=/data \
              --replicas 1 \
              --restart-condition any \
              --update-parallelism 1 \
              --update-delay 30s \
              --update-order start-first \
              --update-failure-action continue \
              --limit-cpu 0.3 \
              --limit-memory 256M \
              --reserve-cpu 0.1 \
              --reserve-memory 128M \
              --with-registry-auth \
              ${{ secrets.DOCKERHUB_USERNAME }}/swecc-redis:latest
          fi

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          timeout=300
          elapsed=0

          echo "Waiting 3 seconds before starting verification..."
          sleep 3

          while [ $elapsed -lt $timeout ]; do
            REPLICAS=$(docker service ls --filter "name=redis" --format "{{.Replicas}}")
            echo "Current replica status: $REPLICAS"

            if [ "$REPLICAS" == "1/1" ]; then
              echo "✅ Service deployed successfully"
              exit 0
            fi

            echo "⏳ Waiting for service to be fully deployed... ($elapsed/$timeout seconds)"
            sleep 10
            elapsed=$((elapsed + 10))

            echo "Current service status:"
            docker service ps redis --no-trunc

            if docker service ps redis --filter "desired-state=running" --format "{{.Error}}" | grep -q .; then
              echo "⚠️ Deployment showing errors, but continuing to wait..."
            fi
          done

          echo "❌ Deployment verification timed out after $timeout seconds"
          echo "Final service status:"
          docker service ps redis --no-trunc
          exit 1